DROP TABLE IF EXISTS inventory;

CREATE TABLE inventory(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item TEXT UNIQUE NOT NULL,
    amount INTEGER NOT NULL
);

CREATE TABLE shopping_list(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item TEXT UNIQUE NOT NULL,
    amount INTEGER NOT NULL
);